# Generated by Django 6.0 on 2025-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('MINT', 'Mint NFT'), ('TRANSFER', 'Transfer Ownership'), ('VERIFY', 'Verify Authenticity')], max_length=20)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('from_address', models.CharField(blank=True, max_length=255, null=True)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blockchain_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFTCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255)),
                ('token_id', models.CharField(max_length=100, unique=True)),
                ('blockchain_network', models.CharField(default='ethereum', max_length=50)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_data', models.JSONField(default=dict)),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('MINTING', 'Minting'), ('MINTED', 'Minted'), ('TRANSFERRED', 'Transferred'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('minted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nft_certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]
