# Generated by Django 6.0 on 2025-12-23 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcertificate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nft_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nftcertificate',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nft_certificate', to='products.product'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='nft_certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.nftcertificate'),
        ),
        migrations.AddIndex(
            model_name='nftcertificate',
            index=models.Index(fields=['token_id'], name='nft_certifi_token_i_84c776_idx'),
        ),
        migrations.AddIndex(
            model_name='nftcertificate',
            index=models.Index(fields=['owner', '-created_at'], name='nft_certifi_owner_i_d80802_idx'),
        ),
        migrations.AddIndex(
            model_name='nftcertificate',
            index=models.Index(fields=['status'], name='nft_certifi_status_65edfc_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_9bd57a_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['nft_certificate', '-created_at'], name='blockchain__nft_cer_9020c1_idx'),
        ),
    ]
