# Generated by Django 6.0 on 2025-12-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('GLB', 'GLB Format'), ('GLTF', 'GLTF Format'), ('USDZ', 'USDZ Format (iOS)')], max_length=10)),
                ('file', models.FileField(upload_to='ar_models/')),
                ('file_size_mb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('polygon_count', models.IntegerField(blank=True, null=True)),
                ('has_textures', models.BooleanField(default=True)),
                ('has_animations', models.BooleanField(default=False)),
                ('is_optimized', models.BooleanField(default=False)),
                ('optimization_level', models.CharField(choices=[('LOW', 'Low Quality'), ('MEDIUM', 'Medium Quality'), ('HIGH', 'High Quality')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_models', to='products.product')),
            ],
            options={
                'db_table': 'ar_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ARSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('screenshots_taken', models.IntegerField(default=0)),
                ('rotation_count', models.IntegerField(default=0)),
                ('zoom_count', models.IntegerField(default=0)),
                ('ar_data', models.JSONField(default=dict, help_text='AR session metadata and measurements')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_sessions', to='products.product')),
            ],
            options={
                'db_table': 'ar_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
