# Generated by Django 6.0 on 2025-12-23 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ar_experience', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='armodel',
            index=models.Index(fields=['product', 'format'], name='ar_models_product_160078_idx'),
        ),
        migrations.AddIndex(
            model_name='arsession',
            index=models.Index(fields=['user', '-started_at'], name='ar_sessions_user_id_8ce398_idx'),
        ),
        migrations.AddIndex(
            model_name='arsession',
            index=models.Index(fields=['product', '-started_at'], name='ar_sessions_product_de9bba_idx'),
        ),
        migrations.AddIndex(
            model_name='arsession',
            index=models.Index(fields=['session_id'], name='ar_sessions_session_f75fc7_idx'),
        ),
    ]
