# Generated by Django 6.0 on 2025-12-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('algorithm', models.CharField(help_text='e.g., collaborative_filtering, content_based', max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('precision', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('recall', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('model_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendation_models',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, help_text='Recommendation confidence score', max_digits=5)),
                ('reason', models.CharField(blank=True, help_text='Why this was recommended', max_length=255)),
                ('based_on_interactions', models.JSONField(default=list, help_text='List of interaction IDs used')),
                ('shown_to_user', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this recommendation expires')),
            ],
            options={
                'db_table': 'user_recommendations',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0)),
                ('total_ar_tries', models.IntegerField(default=0)),
                ('total_3d_interactions', models.IntegerField(default=0)),
                ('avg_session_duration', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_interaction_date', models.DateTimeField()),
                ('engagement_score', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'interaction_features',
            },
        ),
    ]
