# Generated by Django 6.0 on 2025-12-23 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionfeature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendations.recommendationmodel'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='interactionfeature',
            index=models.Index(fields=['user', '-engagement_score'], name='interaction_user_id_03c32d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interactionfeature',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', '-score'], name='user_recomm_user_id_556b02_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendation',
            index=models.Index(fields=['user', 'shown_to_user'], name='user_recomm_user_id_ad8926_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrecommendation',
            unique_together={('user', 'product', 'model')},
        ),
    ]
